server:
  port: 8080
  tomcat:
      max-threads: 200

spring:
  datasource:
    driverClassName: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://192.168.99.100:3306/sampleDB?useUnicode=true&characterEncoding=utf8
    username: root
    password: ail733
    testWhileIdle: true
    validationQuery: SELECT 1

jpa:
    generate-ddl: false

logging:
  level:
    root: ERROR

#
#security:
#  ignored: true
#  basic:
#    enabled: false




